name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Newman and Newman Reporter HTML
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run API tests
        run: |
          newman run "Restful Booker BVT.postman_collection.json" \
            -e Restful_Booker_Prod.postman_environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman-results.html
      - name: Upload Newman results
        uses: actions/upload-artifact@v3
        with:
          name: newman-results
          path: newman-results.html
